name: self-hosted-example

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - name: Run a multi-line script
	  run : echo on
            echo "Great day ahead"
			timeout /t 5000
